/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario1;

/**
 *
 * @author Miguel Castillo
 */
public class Evaluacion3 extends javax.swing.JFrame {

  public static int cont2;
    public Evaluacion3() {
        initComponents();
            jLabelPRE9.setEnabled(true);
            jRadioRES25.setEnabled(true);
            jRadioRES26.setEnabled(true);
            jRadioRES27.setEnabled(true);
            jLabelPRE10.setEnabled(false);
            jRadioRES28.setEnabled(false);
            jRadioRES29.setEnabled(false);
            jRadioRES30.setEnabled(false);
            jLabelPRE11.setEnabled(false);
            jRadioRES31.setEnabled(false);
            jRadioRES32.setEnabled(false);
            jRadioRES33.setEnabled(false);
            jLabelPRE12.setEnabled(false);
            jRadioRES34.setEnabled(false);
            jRadioRES35.setEnabled(false);
            jRadioRES36.setEnabled(false);
            jButton2.setEnabled(false);
            jB1.setEnabled(false);
            jB2.setEnabled(false);
            jB3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPRE9 = new javax.swing.JLabel();
        jLabelPRE10 = new javax.swing.JLabel();
        jLabelPRE11 = new javax.swing.JLabel();
        jLabelPRE12 = new javax.swing.JLabel();
        jRadioRES25 = new javax.swing.JRadioButton();
        jRadioRES26 = new javax.swing.JRadioButton();
        jRadioRES27 = new javax.swing.JRadioButton();
        jRadioRES28 = new javax.swing.JRadioButton();
        jRadioRES29 = new javax.swing.JRadioButton();
        jRadioRES30 = new javax.swing.JRadioButton();
        jRadioRES31 = new javax.swing.JRadioButton();
        jRadioRES32 = new javax.swing.JRadioButton();
        jRadioRES33 = new javax.swing.JRadioButton();
        jRadioRES34 = new javax.swing.JRadioButton();
        jRadioRES35 = new javax.swing.JRadioButton();
        jRadioRES36 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CUESTIONARIO DE CAPITALES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 23, 560, 43);

        jLabelPRE9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE9.setText("9. CAPITAL DE ALEMANIA:");
        getContentPane().add(jLabelPRE9);
        jLabelPRE9.setBounds(10, 97, 190, 17);

        jLabelPRE10.setFont(jLabelPRE10.getFont().deriveFont((jLabelPRE10.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelPRE10.getFont().getSize()+3));
        jLabelPRE10.setText("10. CAPITAL DE AUSTRALIA:");
        getContentPane().add(jLabelPRE10);
        jLabelPRE10.setBounds(10, 215, 220, 17);

        jLabelPRE11.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE11.setText("11. CAPITAL DE CHILE:");
        getContentPane().add(jLabelPRE11);
        jLabelPRE11.setBounds(10, 331, 190, 17);

        jLabelPRE12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE12.setText("12. CAPITAL DE CANADA:");
        getContentPane().add(jLabelPRE12);
        jLabelPRE12.setBounds(10, 447, 174, 17);

        jRadioRES25.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES25.setText("MUNICH");
        jRadioRES25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES25ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES25);
        jRadioRES25.setBounds(10, 113, 180, 25);

        jRadioRES26.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES26.setText("BERLIN");
        jRadioRES26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES26ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES26);
        jRadioRES26.setBounds(10, 138, 180, 25);

        jRadioRES27.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES27.setText("HAMBURGO");
        jRadioRES27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES27ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES27);
        jRadioRES27.setBounds(10, 161, 180, 25);

        jRadioRES28.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES28.setText("BRISBANE");
        jRadioRES28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES28ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES28);
        jRadioRES28.setBounds(10, 231, 210, 25);

        jRadioRES29.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES29.setText("DARWIN");
        jRadioRES29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES29ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES29);
        jRadioRES29.setBounds(10, 254, 210, 25);

        jRadioRES30.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES30.setText("SIDNEY");
        jRadioRES30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES30ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES30);
        jRadioRES30.setBounds(10, 277, 210, 25);

        jRadioRES31.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES31.setText("SANTIAGO DE CHILE");
        jRadioRES31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES31ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES31);
        jRadioRES31.setBounds(10, 347, 170, 25);

        jRadioRES32.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES32.setText("CONCEPCION");
        jRadioRES32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES32ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES32);
        jRadioRES32.setBounds(10, 370, 170, 25);

        jRadioRES33.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES33.setText("VALDIVIA");
        jRadioRES33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES33ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES33);
        jRadioRES33.setBounds(10, 393, 170, 25);

        jRadioRES34.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES34.setText("OTTAWA");
        jRadioRES34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES34ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES34);
        jRadioRES34.setBounds(10, 463, 170, 25);

        jRadioRES35.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES35.setText("TORONTO");
        jRadioRES35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES35ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES35);
        jRadioRES35.setBounds(10, 486, 170, 25);

        jRadioRES36.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES36.setText("QUEBEC");
        jRadioRES36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES36ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES36);
        jRadioRES36.setBounds(10, 509, 170, 25);

        jButton2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("SIGUIENTE HOJA");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 440, 180, 90);

        jB1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB1.setText("SIGUIENTE PREGUNTA");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1);
        jB1.setBounds(280, 140, 180, 40);

        jB2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB2.setText("SIGUIENTE PREGUNTA");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB2);
        jB2.setBounds(280, 240, 180, 40);

        jB3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB3.setText("SIGUIENTE PREGUNTA");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3);
        jB3.setBounds(280, 350, 180, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario1/cuestionarios.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioRES25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES25ActionPerformed
        jRadioRES26.setEnabled(false);
        jRadioRES27.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES25ActionPerformed

    private void jRadioRES26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES26ActionPerformed
        jRadioRES26.isSelected();
        cont2=cont2+10;
        jRadioRES25.setEnabled(false);
        jRadioRES27.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES26ActionPerformed

    private void jRadioRES28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES28ActionPerformed
        jRadioRES30.setEnabled(false);
        jRadioRES29.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES28ActionPerformed

    private void jRadioRES30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES30ActionPerformed
        jRadioRES30.isSelected();
        cont2=cont2+10;
        jRadioRES29.setEnabled(false);
        jRadioRES28.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES30ActionPerformed

    private void jRadioRES31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES31ActionPerformed
        jRadioRES31.isSelected();
        cont2=cont2+10;
        jRadioRES32.setEnabled(false);
        jRadioRES33.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES31ActionPerformed

    private void jRadioRES34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES34ActionPerformed
        jRadioRES34.isSelected();
        cont2=cont2+10;
        jRadioRES35.setEnabled(false);
        jRadioRES36.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES34ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Evaluacion4 opc=new Evaluacion4();
        opc.setVisible(true);
        opc.setSize(950,600);
        Evaluacion2 cap=new Evaluacion2();
        cont2=cap.cont1+cont2;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioRES27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES27ActionPerformed
        jRadioRES26.setEnabled(false);
        jRadioRES25.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES27ActionPerformed

    private void jRadioRES32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES32ActionPerformed
       jRadioRES31.setEnabled(false);
       jRadioRES33.setEnabled(false);
       jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES32ActionPerformed

    private void jRadioRES35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES35ActionPerformed
        jRadioRES34.setEnabled(false);
        jRadioRES36.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES35ActionPerformed

    private void jRadioRES29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES29ActionPerformed
        jRadioRES28.setEnabled(false);
        jRadioRES30.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES29ActionPerformed

    private void jRadioRES33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES33ActionPerformed
        jRadioRES31.setEnabled(false);
        jRadioRES32.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES33ActionPerformed

    private void jRadioRES36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES36ActionPerformed
        jRadioRES34.setEnabled(false);
        jRadioRES35.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES36ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        jLabelPRE10.setEnabled(true);
        jRadioRES28.setEnabled(true);
        jRadioRES29.setEnabled(true);
        jRadioRES30.setEnabled(true);

    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        jLabelPRE11.setEnabled(true);
        jRadioRES31.setEnabled(true);
        jRadioRES32.setEnabled(true);
        jRadioRES33.setEnabled(true);

    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        jLabelPRE12.setEnabled(true);
        jRadioRES34.setEnabled(true);
        jRadioRES35.setEnabled(true);
        jRadioRES36.setEnabled(true);
    }//GEN-LAST:event_jB3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Evaluacion3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPRE10;
    private javax.swing.JLabel jLabelPRE11;
    private javax.swing.JLabel jLabelPRE12;
    private javax.swing.JLabel jLabelPRE9;
    private javax.swing.JRadioButton jRadioRES25;
    private javax.swing.JRadioButton jRadioRES26;
    private javax.swing.JRadioButton jRadioRES27;
    private javax.swing.JRadioButton jRadioRES28;
    private javax.swing.JRadioButton jRadioRES29;
    private javax.swing.JRadioButton jRadioRES30;
    private javax.swing.JRadioButton jRadioRES31;
    private javax.swing.JRadioButton jRadioRES32;
    private javax.swing.JRadioButton jRadioRES33;
    private javax.swing.JRadioButton jRadioRES34;
    private javax.swing.JRadioButton jRadioRES35;
    private javax.swing.JRadioButton jRadioRES36;
    // End of variables declaration//GEN-END:variables
}
