/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario1;

/**
 *
 * @author Miguel Castillo
 */
public class Evaluacion5 extends javax.swing.JFrame {

  public static int cont4;
    public Evaluacion5() {
        initComponents();
            jLabelPRE17.setEnabled(true);
            jRadioRES49.setEnabled(true);
            jRadioRES50.setEnabled(true);
            jRadioRES51.setEnabled(true);
            jLabelPRE18.setEnabled(false);
            jRadioRES52.setEnabled(false);
            jRadioRES53.setEnabled(false);
            jRadioRES54.setEnabled(false);
            jLabelPRE19.setEnabled(false);
            jRadioRES55.setEnabled(false);
            jRadioRES56.setEnabled(false);
            jRadioRES57.setEnabled(false);
            jLabelPRE20.setEnabled(false);
            jRadioRES58.setEnabled(false);
            jRadioRES59.setEnabled(false);
            jRadioRES60.setEnabled(false);
            jB1.setEnabled(false);
            jB2.setEnabled(false);
            jB3.setEnabled(false);
            jButtonRESULTADO.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRESULTADO = new javax.swing.JButton();
        jTextR = new javax.swing.JTextField();
        jRadioRES49 = new javax.swing.JRadioButton();
        jRadioRES50 = new javax.swing.JRadioButton();
        jRadioRES51 = new javax.swing.JRadioButton();
        jRadioRES52 = new javax.swing.JRadioButton();
        jRadioRES53 = new javax.swing.JRadioButton();
        jRadioRES54 = new javax.swing.JRadioButton();
        jRadioRES55 = new javax.swing.JRadioButton();
        jRadioRES56 = new javax.swing.JRadioButton();
        jRadioRES57 = new javax.swing.JRadioButton();
        jRadioRES58 = new javax.swing.JRadioButton();
        jRadioRES59 = new javax.swing.JRadioButton();
        jRadioRES60 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelPRE17 = new javax.swing.JLabel();
        jLabelPRE18 = new javax.swing.JLabel();
        jLabelPRE19 = new javax.swing.JLabel();
        jLabelPRE20 = new javax.swing.JLabel();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonRESULTADO.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButtonRESULTADO.setForeground(new java.awt.Color(0, 0, 153));
        jButtonRESULTADO.setText("RESULTADO");
        jButtonRESULTADO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESULTADOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRESULTADO);
        jButtonRESULTADO.setBounds(670, 280, 188, 50);

        jTextR.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jTextR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jTextR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextR);
        jTextR.setBounds(669, 342, 188, 60);

        jRadioRES49.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES49.setText("MANDEVILLE");
        jRadioRES49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES49ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES49);
        jRadioRES49.setBounds(10, 113, 170, 25);

        jRadioRES50.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES50.setText("KINGSTONE");
        jRadioRES50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES50ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES50);
        jRadioRES50.setBounds(10, 138, 170, 25);

        jRadioRES51.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES51.setText("NEGRIL");
        jRadioRES51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES51ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES51);
        jRadioRES51.setBounds(10, 161, 170, 25);

        jRadioRES52.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES52.setText("VIÑALES");
        jRadioRES52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES52ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES52);
        jRadioRES52.setBounds(10, 231, 160, 25);

        jRadioRES53.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES53.setText("TRINIDAD");
        jRadioRES53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES53ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES53);
        jRadioRES53.setBounds(10, 254, 160, 25);

        jRadioRES54.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES54.setText("HABANA");
        jRadioRES54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES54ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES54);
        jRadioRES54.setBounds(10, 277, 160, 25);

        jRadioRES55.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES55.setText("BRASILIA");
        jRadioRES55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES55ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES55);
        jRadioRES55.setBounds(10, 347, 160, 25);

        jRadioRES56.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES56.setText("RIO DE JANEIRO");
        jRadioRES56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES56ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES56);
        jRadioRES56.setBounds(10, 370, 160, 25);

        jRadioRES57.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES57.setText("SAO PAULO");
        jRadioRES57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES57ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES57);
        jRadioRES57.setBounds(10, 393, 160, 25);

        jRadioRES58.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES58.setText("BERNA");
        jRadioRES58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES58ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES58);
        jRadioRES58.setBounds(10, 463, 160, 25);

        jRadioRES59.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES59.setText("ZURICH");
        jRadioRES59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES59ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES59);
        jRadioRES59.setBounds(10, 486, 160, 25);

        jRadioRES60.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES60.setText("BASILEA");
        jRadioRES60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES60ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES60);
        jRadioRES60.setBounds(10, 509, 160, 25);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CUESTIONARIO DE CAPITALES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 23, 547, 43);

        jLabelPRE17.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE17.setText("17. CAPITAL DE JAMAICA:");
        getContentPane().add(jLabelPRE17);
        jLabelPRE17.setBounds(10, 97, 300, 17);

        jLabelPRE18.setFont(jLabelPRE18.getFont().deriveFont((jLabelPRE18.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelPRE18.getFont().getSize()+3));
        jLabelPRE18.setText("18. CAPITAL DE CUBA:");
        getContentPane().add(jLabelPRE18);
        jLabelPRE18.setBounds(10, 215, 340, 17);

        jLabelPRE19.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE19.setText("19. CAPITAL DE BRASIL:");
        getContentPane().add(jLabelPRE19);
        jLabelPRE19.setBounds(10, 331, 190, 17);

        jLabelPRE20.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE20.setText("20. CAPITAL DE SUIZA:");
        getContentPane().add(jLabelPRE20);
        jLabelPRE20.setBounds(10, 447, 155, 17);

        jB1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB1.setText("SIGUIENTE PREGUNTA");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1);
        jB1.setBounds(280, 140, 180, 40);

        jB2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB2.setText("SIGUIENTE PREGUNTA");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB2);
        jB2.setBounds(280, 240, 180, 40);

        jB3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB3.setText("SIGUIENTE PREGUNTA");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3);
        jB3.setBounds(280, 350, 180, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario1/cuestionarios.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESULTADOActionPerformed
      Evaluacion4 cap=new Evaluacion4();
      cont4=cap.cont3+cont4;
        jTextR.setText(String.valueOf(cont4));  
    }//GEN-LAST:event_jButtonRESULTADOActionPerformed

    private void jRadioRES54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES54ActionPerformed
        jRadioRES54.isSelected();
        cont4=cont4+10;
        jRadioRES53.setEnabled(false);
        jRadioRES52.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES54ActionPerformed

    private void jRadioRES55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES55ActionPerformed
        jRadioRES55.isSelected();
        cont4=cont4+10;
        jRadioRES56.setEnabled(false);
        jRadioRES57.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES55ActionPerformed

    private void jRadioRES56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES56ActionPerformed
        jRadioRES55.setEnabled(false);
        jRadioRES57.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES56ActionPerformed

    private void jRadioRES58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES58ActionPerformed
        jRadioRES58.isSelected();
        cont4=cont4+10;
        jRadioRES59.setEnabled(false);
        jRadioRES60.setEnabled(false);
        jButtonRESULTADO.setEnabled(true);
    }//GEN-LAST:event_jRadioRES58ActionPerformed

    private void jRadioRES59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES59ActionPerformed
        jRadioRES58.setEnabled(false);
        jRadioRES60.setEnabled(false);
        jButtonRESULTADO.setEnabled(true);
    }//GEN-LAST:event_jRadioRES59ActionPerformed

    private void jRadioRES49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES49ActionPerformed
        jRadioRES50.setEnabled(false);
        jRadioRES51.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES49ActionPerformed

    private void jRadioRES50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES50ActionPerformed
        jRadioRES50.isSelected();
        cont4=cont4+10;
        jRadioRES49.setEnabled(false);
        jRadioRES51.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES50ActionPerformed

    private void jRadioRES51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES51ActionPerformed
        jRadioRES50.setEnabled(false);
        jRadioRES49.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES51ActionPerformed

    private void jRadioRES52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES52ActionPerformed
        jRadioRES54.setEnabled(false);
        jRadioRES53.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES52ActionPerformed

    private void jRadioRES53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES53ActionPerformed
        jRadioRES54.setEnabled(false);
        jRadioRES52.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES53ActionPerformed

    private void jRadioRES57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES57ActionPerformed
         jRadioRES55.setEnabled(false);
         jRadioRES56.setEnabled(false);
         jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES57ActionPerformed

    private void jRadioRES60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES60ActionPerformed
        jRadioRES58.setEnabled(false);
        jRadioRES59.setEnabled(false);
        jButtonRESULTADO.setEnabled(true);
    }//GEN-LAST:event_jRadioRES60ActionPerformed

    private void jTextRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        jLabelPRE18.setEnabled(true);
        jRadioRES52.setEnabled(true);
        jRadioRES53.setEnabled(true);
        jRadioRES54.setEnabled(true);
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        jLabelPRE19.setEnabled(true);
        jRadioRES55.setEnabled(true);
        jRadioRES56.setEnabled(true);
        jRadioRES57.setEnabled(true);
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        jLabelPRE20.setEnabled(true);
        jRadioRES58.setEnabled(true);
        jRadioRES59.setEnabled(true);
        jRadioRES60.setEnabled(true);
    }//GEN-LAST:event_jB3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Evaluacion5().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jButtonRESULTADO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPRE17;
    private javax.swing.JLabel jLabelPRE18;
    private javax.swing.JLabel jLabelPRE19;
    private javax.swing.JLabel jLabelPRE20;
    private javax.swing.JRadioButton jRadioRES49;
    private javax.swing.JRadioButton jRadioRES50;
    private javax.swing.JRadioButton jRadioRES51;
    private javax.swing.JRadioButton jRadioRES52;
    private javax.swing.JRadioButton jRadioRES53;
    private javax.swing.JRadioButton jRadioRES54;
    private javax.swing.JRadioButton jRadioRES55;
    private javax.swing.JRadioButton jRadioRES56;
    private javax.swing.JRadioButton jRadioRES57;
    private javax.swing.JRadioButton jRadioRES58;
    private javax.swing.JRadioButton jRadioRES59;
    private javax.swing.JRadioButton jRadioRES60;
    private javax.swing.JTextField jTextR;
    // End of variables declaration//GEN-END:variables
}
