/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario1;

/**
 *
 * @author Miguel Castillo
 */
public class Evaluacion1 extends javax.swing.JFrame {
    
    public static int cont;
        public Evaluacion1() {
            initComponents();
            jLabelPRE1.setEnabled(false);
            jRadioRES1.setEnabled(false);
            jRadioRES2.setEnabled(false);
            jRadioRES3.setEnabled(false);
            jLabelPRE2.setEnabled(false);
            jRadioRES4.setEnabled(false);
            jRadioRES5.setEnabled(false);
            jRadioRES6.setEnabled(false);
            jLabelPRE3.setEnabled(false);
            jRadioRES7.setEnabled(false);
            jRadioRES8.setEnabled(false);
            jRadioRES9.setEnabled(false);
            jLabelPRE4.setEnabled(false);
            jRadioRES10.setEnabled(false);
            jRadioRES11.setEnabled(false);
            jRadioRES12.setEnabled(false);
            jB1.setEnabled(false);
            jB2.setEnabled(false);
            jB3.setEnabled(false);
            jButton2.setEnabled(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabelPRE1 = new javax.swing.JLabel();
        jLabelPRE2 = new javax.swing.JLabel();
        jLabelPRE3 = new javax.swing.JLabel();
        jLabelPRE4 = new javax.swing.JLabel();
        jRadioRES1 = new javax.swing.JRadioButton();
        jRadioRES2 = new javax.swing.JRadioButton();
        jRadioRES3 = new javax.swing.JRadioButton();
        jRadioRES4 = new javax.swing.JRadioButton();
        jRadioRES5 = new javax.swing.JRadioButton();
        jRadioRES6 = new javax.swing.JRadioButton();
        jRadioRES7 = new javax.swing.JRadioButton();
        jRadioRES8 = new javax.swing.JRadioButton();
        jRadioRES9 = new javax.swing.JRadioButton();
        jRadioRES10 = new javax.swing.JRadioButton();
        jRadioRES11 = new javax.swing.JRadioButton();
        jRadioRES12 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CUESTIONARIO DE CAPITALES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 23, 547, 43);

        jLabelPRE1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE1.setText("1. CAPITAL DE COLOMBIA:");
        getContentPane().add(jLabelPRE1);
        jLabelPRE1.setBounds(10, 97, 190, 17);

        jLabelPRE2.setFont(jLabelPRE2.getFont().deriveFont((jLabelPRE2.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelPRE2.getFont().getSize()+3));
        jLabelPRE2.setText("2. CAPITAL DE PERU:");
        getContentPane().add(jLabelPRE2);
        jLabelPRE2.setBounds(10, 215, 160, 17);

        jLabelPRE3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE3.setText("3. CAPITAL DE ARGENTINA:");
        getContentPane().add(jLabelPRE3);
        jLabelPRE3.setBounds(10, 331, 190, 17);

        jLabelPRE4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE4.setText("4. CAPITAL DE MEXICO:");
        getContentPane().add(jLabelPRE4);
        jLabelPRE4.setBounds(10, 447, 161, 17);

        buttonGroup1.add(jRadioRES1);
        jRadioRES1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES1.setText("BARRANQUILLA");
        jRadioRES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES1);
        jRadioRES1.setBounds(10, 113, 180, 25);

        buttonGroup1.add(jRadioRES2);
        jRadioRES2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES2.setText("BOGOTA");
        jRadioRES2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES2);
        jRadioRES2.setBounds(10, 138, 180, 25);

        buttonGroup1.add(jRadioRES3);
        jRadioRES3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES3.setText("MEDELLIN");
        jRadioRES3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES3);
        jRadioRES3.setBounds(10, 161, 180, 25);

        buttonGroup2.add(jRadioRES4);
        jRadioRES4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES4.setText("CUSCO");
        jRadioRES4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES4);
        jRadioRES4.setBounds(10, 231, 150, 25);

        buttonGroup2.add(jRadioRES5);
        jRadioRES5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES5.setText("TRUJILLO");
        jRadioRES5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES5);
        jRadioRES5.setBounds(10, 254, 150, 25);

        buttonGroup2.add(jRadioRES6);
        jRadioRES6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES6.setText("LIMA");
        jRadioRES6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES6);
        jRadioRES6.setBounds(10, 277, 150, 25);

        buttonGroup3.add(jRadioRES7);
        jRadioRES7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES7.setText("BUENOS AIRES");
        jRadioRES7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES7);
        jRadioRES7.setBounds(10, 347, 190, 25);

        buttonGroup3.add(jRadioRES8);
        jRadioRES8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES8.setText("LA PLATA");
        jRadioRES8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES8);
        jRadioRES8.setBounds(10, 370, 190, 25);

        buttonGroup3.add(jRadioRES9);
        jRadioRES9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES9.setText("CORDODA");
        jRadioRES9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES9ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES9);
        jRadioRES9.setBounds(10, 393, 190, 25);

        buttonGroup4.add(jRadioRES10);
        jRadioRES10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES10.setText("MEXICO");
        jRadioRES10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES10ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES10);
        jRadioRES10.setBounds(10, 463, 160, 25);

        buttonGroup4.add(jRadioRES11);
        jRadioRES11.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES11.setText("CANCUN");
        jRadioRES11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES11ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES11);
        jRadioRES11.setBounds(10, 486, 160, 25);

        buttonGroup4.add(jRadioRES12);
        jRadioRES12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES12.setText("GUADALAJARA");
        jRadioRES12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES12ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES12);
        jRadioRES12.setBounds(10, 509, 160, 25);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("INICIAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 80, 179, 94);

        jButton2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("SIGUIENTE HOJA");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 460, 180, 70);

        jB1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB1.setText("SIGUIENTE PREGUNTA");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1);
        jB1.setBounds(240, 143, 170, 40);

        jB3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB3.setText("SIGUIENTE PREGUNTA");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3);
        jB3.setBounds(240, 370, 170, 40);

        jB2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB2.setText("SIGUIENTE PREGUNTA");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB2);
        jB2.setBounds(240, 253, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario1/cuestionarios.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 920, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            jLabelPRE1.setEnabled(true);
            jRadioRES1.setEnabled(true);
            jRadioRES2.setEnabled(true);
            jRadioRES3.setEnabled(true);       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioRES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES1ActionPerformed
       jRadioRES2.setEnabled(false);
       jRadioRES3.setEnabled(false);
       jB1.setEnabled(true); 
    }//GEN-LAST:event_jRadioRES1ActionPerformed

    private void jRadioRES2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES2ActionPerformed
       jRadioRES2.isSelected();
       cont=cont+10; 
       jRadioRES1.setEnabled(false);
       jRadioRES3.setEnabled(false);  
       jB1.setEnabled(true); 
    }//GEN-LAST:event_jRadioRES2ActionPerformed

    private void jRadioRES6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES6ActionPerformed
       jRadioRES6.isSelected();
       cont=cont+10; 
       jRadioRES4.setEnabled(false);
       jRadioRES5.setEnabled(false);
       jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES6ActionPerformed

    private void jRadioRES4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES4ActionPerformed
       jRadioRES5.setEnabled(false);
       jRadioRES6.setEnabled(false);
       jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES4ActionPerformed

    private void jRadioRES7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES7ActionPerformed
        jRadioRES7.isSelected();
        cont=cont+10;
        jRadioRES8.setEnabled(false);
        jRadioRES9.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES7ActionPerformed

    private void jRadioRES10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES10ActionPerformed
        jRadioRES10.isSelected();
        cont=cont+10;
        jRadioRES11.setEnabled(false);
        jRadioRES12.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Evaluacion2 op=new Evaluacion2();
        op.setVisible(true);
        op.setSize(950,600);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioRES5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES5ActionPerformed
       jRadioRES4.setEnabled(false);
       jRadioRES6.setEnabled(false);
       jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES5ActionPerformed

    private void jRadioRES8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES8ActionPerformed
       jRadioRES7.setEnabled(false);
       jRadioRES9.setEnabled(false);
       jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES8ActionPerformed

    private void jRadioRES11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES11ActionPerformed
       jRadioRES10.setEnabled(false);
       jRadioRES12.setEnabled(false);
       jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES11ActionPerformed

    private void jRadioRES3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES3ActionPerformed
       jRadioRES1.setEnabled(false);
       jRadioRES2.setEnabled(false);
       jB1.setEnabled(true); 
    }//GEN-LAST:event_jRadioRES3ActionPerformed

    private void jRadioRES9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES9ActionPerformed
        jRadioRES7.setEnabled(false);
        jRadioRES8.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES9ActionPerformed

    private void jRadioRES12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES12ActionPerformed
       jRadioRES10.setEnabled(false);
       jRadioRES11.setEnabled(false);
       jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES12ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
          jLabelPRE2.setEnabled(true);
          jRadioRES4.setEnabled(true);
          jRadioRES5.setEnabled(true);
          jRadioRES6.setEnabled(true);
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
            jLabelPRE3.setEnabled(true);
            jRadioRES7.setEnabled(true);
            jRadioRES8.setEnabled(true);
            jRadioRES9.setEnabled(true);
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
            jLabelPRE4.setEnabled(true);
            jRadioRES10.setEnabled(true);
            jRadioRES11.setEnabled(true);
            jRadioRES12.setEnabled(true);
    }//GEN-LAST:event_jB3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Evaluacion1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPRE1;
    private javax.swing.JLabel jLabelPRE2;
    private javax.swing.JLabel jLabelPRE3;
    private javax.swing.JLabel jLabelPRE4;
    private javax.swing.JRadioButton jRadioRES1;
    private javax.swing.JRadioButton jRadioRES10;
    private javax.swing.JRadioButton jRadioRES11;
    private javax.swing.JRadioButton jRadioRES12;
    private javax.swing.JRadioButton jRadioRES2;
    private javax.swing.JRadioButton jRadioRES3;
    private javax.swing.JRadioButton jRadioRES4;
    private javax.swing.JRadioButton jRadioRES5;
    private javax.swing.JRadioButton jRadioRES6;
    private javax.swing.JRadioButton jRadioRES7;
    private javax.swing.JRadioButton jRadioRES8;
    private javax.swing.JRadioButton jRadioRES9;
    // End of variables declaration//GEN-END:variables
}
