/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario1;

/**
 *
 * @author Miguel Castillo
 */
public class Evaluacion4 extends javax.swing.JFrame {
public static int cont3;
    public Evaluacion4() {
        initComponents();
            jLabelPRE13.setEnabled(true);
            jRadioRES37.setEnabled(true);
            jRadioRES38.setEnabled(true);
            jRadioRES39.setEnabled(true);
            jLabelPRE14.setEnabled(false);
            jRadioRES40.setEnabled(false);
            jRadioRES41.setEnabled(false);
            jRadioRES42.setEnabled(false);
            jLabelPRE15.setEnabled(false);
            jRadioRES43.setEnabled(false);
            jRadioRES44.setEnabled(false);
            jRadioRES45.setEnabled(false);
            jLabelPRE16.setEnabled(false);
            jRadioRES46.setEnabled(false);
            jRadioRES47.setEnabled(false);
            jRadioRES48.setEnabled(false);
            jButton2.setEnabled(false);
            jB1.setEnabled(false);
            jB2.setEnabled(false);
            jB3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioRES37 = new javax.swing.JRadioButton();
        jRadioRES38 = new javax.swing.JRadioButton();
        jRadioRES39 = new javax.swing.JRadioButton();
        jRadioRES40 = new javax.swing.JRadioButton();
        jRadioRES41 = new javax.swing.JRadioButton();
        jRadioRES42 = new javax.swing.JRadioButton();
        jRadioRES43 = new javax.swing.JRadioButton();
        jRadioRES44 = new javax.swing.JRadioButton();
        jRadioRES45 = new javax.swing.JRadioButton();
        jRadioRES46 = new javax.swing.JRadioButton();
        jRadioRES47 = new javax.swing.JRadioButton();
        jRadioRES48 = new javax.swing.JRadioButton();
        jLabelPRE13 = new javax.swing.JLabel();
        jLabelPRE14 = new javax.swing.JLabel();
        jLabelPRE15 = new javax.swing.JLabel();
        jLabelPRE16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CUESTIONARIO DE CAPITALES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 23, 560, 43);

        jRadioRES37.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES37.setText("SAN CRISTOBAL");
        jRadioRES37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES37ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES37);
        jRadioRES37.setBounds(10, 113, 190, 25);

        jRadioRES38.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES38.setText("CARACAS");
        jRadioRES38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES38ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES38);
        jRadioRES38.setBounds(10, 138, 190, 20);

        jRadioRES39.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES39.setText("MARACAY");
        jRadioRES39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES39ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES39);
        jRadioRES39.setBounds(10, 155, 190, 30);

        jRadioRES40.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES40.setText("XIAMEN");
        jRadioRES40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES40ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES40);
        jRadioRES40.setBounds(10, 231, 170, 25);

        jRadioRES41.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES41.setText("SHANGHAI");
        jRadioRES41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES41ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES41);
        jRadioRES41.setBounds(10, 254, 170, 25);

        jRadioRES42.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES42.setText("PEKIN");
        jRadioRES42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES42ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES42);
        jRadioRES42.setBounds(10, 277, 170, 25);

        jRadioRES43.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES43.setText("QUITO");
        jRadioRES43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES43ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES43);
        jRadioRES43.setBounds(10, 347, 190, 25);

        jRadioRES44.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES44.setText("MANTA");
        jRadioRES44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES44ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES44);
        jRadioRES44.setBounds(10, 370, 190, 25);

        jRadioRES45.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES45.setText("CUENCA");
        jRadioRES45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES45ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES45);
        jRadioRES45.setBounds(10, 393, 190, 25);

        jRadioRES46.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES46.setText("PANAMA");
        jRadioRES46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES46ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES46);
        jRadioRES46.setBounds(10, 463, 180, 25);

        jRadioRES47.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES47.setText("CHITRE");
        jRadioRES47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES47ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES47);
        jRadioRES47.setBounds(10, 486, 180, 25);

        jRadioRES48.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jRadioRES48.setText("COLON");
        jRadioRES48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRES48ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioRES48);
        jRadioRES48.setBounds(10, 509, 180, 25);

        jLabelPRE13.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE13.setText("13. CAPITAL DE VENEZUELA:");
        getContentPane().add(jLabelPRE13);
        jLabelPRE13.setBounds(10, 97, 300, 17);

        jLabelPRE14.setFont(jLabelPRE14.getFont().deriveFont((jLabelPRE14.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelPRE14.getFont().getSize()+3));
        jLabelPRE14.setText("14. CAPITAL DE CHINA:");
        getContentPane().add(jLabelPRE14);
        jLabelPRE14.setBounds(10, 215, 340, 17);

        jLabelPRE15.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE15.setText("15. CAPITAL DE ECUADOR:");
        getContentPane().add(jLabelPRE15);
        jLabelPRE15.setBounds(10, 331, 190, 17);

        jLabelPRE16.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelPRE16.setText("16. CAPITAL DE PANAMA:");
        getContentPane().add(jLabelPRE16);
        jLabelPRE16.setBounds(10, 447, 174, 17);

        jButton2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("SIGUIENTE HOJA");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 440, 180, 90);

        jB1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB1.setText("SIGUIENTE PREGUNTA");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1);
        jB1.setBounds(280, 140, 180, 40);

        jB2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB2.setText("SIGUIENTE PREGUNTA");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB2);
        jB2.setBounds(280, 240, 180, 40);

        jB3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jB3.setText("SIGUIENTE PREGUNTA");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3);
        jB3.setBounds(280, 350, 180, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formulario1/cuestionarios.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioRES42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES42ActionPerformed
        jRadioRES42.isSelected();
        cont3=cont3+10;
        jRadioRES41.setEnabled(false);
        jRadioRES40.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES42ActionPerformed

    private void jRadioRES43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES43ActionPerformed
        jRadioRES43.isSelected();
        cont3=cont3+10;
        jRadioRES44.setEnabled(false);
        jRadioRES45.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES43ActionPerformed

    private void jRadioRES44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES44ActionPerformed
        jRadioRES43.setEnabled(false);
        jRadioRES45.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES44ActionPerformed

    private void jRadioRES46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES46ActionPerformed
        jRadioRES46.isSelected();
        cont3=cont3+10;
        jRadioRES47.setEnabled(false);
        jRadioRES48.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES46ActionPerformed

    private void jRadioRES47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES47ActionPerformed
        jRadioRES46.setEnabled(false);
        jRadioRES48.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES47ActionPerformed

    private void jRadioRES37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES37ActionPerformed
        jRadioRES38.setEnabled(false);
        jRadioRES39.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES37ActionPerformed

    private void jRadioRES38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES38ActionPerformed
        jRadioRES38.isSelected();
        cont3=cont3+10;
        jRadioRES37.setEnabled(false);
        jRadioRES39.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES38ActionPerformed

    private void jRadioRES39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES39ActionPerformed
        jRadioRES37.setEnabled(false);
        jRadioRES38.setEnabled(false);
        jB1.setEnabled(true);
    }//GEN-LAST:event_jRadioRES39ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Evaluacion5 opc=new Evaluacion5();
        opc.setVisible(true);
        opc.setSize(950,600);
        Evaluacion3 cap=new Evaluacion3();
        cont3=cap.cont2+cont3;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioRES40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES40ActionPerformed
        jRadioRES42.setEnabled(false);
        jRadioRES41.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES40ActionPerformed

    private void jRadioRES41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES41ActionPerformed
        jRadioRES42.setEnabled(false);
        jRadioRES40.setEnabled(false);
        jB2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES41ActionPerformed

    private void jRadioRES45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES45ActionPerformed
        jRadioRES43.setEnabled(false);
        jRadioRES44.setEnabled(false);
        jB3.setEnabled(true);
    }//GEN-LAST:event_jRadioRES45ActionPerformed

    private void jRadioRES48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRES48ActionPerformed
        jRadioRES46.setEnabled(false);
        jRadioRES47.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jRadioRES48ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        jLabelPRE14.setEnabled(true);
        jRadioRES40.setEnabled(true);
        jRadioRES41.setEnabled(true);
        jRadioRES42.setEnabled(true);
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        jLabelPRE15.setEnabled(true);
        jRadioRES43.setEnabled(true);
        jRadioRES44.setEnabled(true);
        jRadioRES45.setEnabled(true);
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        jLabelPRE16.setEnabled(true);
        jRadioRES46.setEnabled(true);
        jRadioRES47.setEnabled(true);
        jRadioRES48.setEnabled(true);
    }//GEN-LAST:event_jB3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluacion4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPRE13;
    private javax.swing.JLabel jLabelPRE14;
    private javax.swing.JLabel jLabelPRE15;
    private javax.swing.JLabel jLabelPRE16;
    private javax.swing.JRadioButton jRadioRES37;
    private javax.swing.JRadioButton jRadioRES38;
    private javax.swing.JRadioButton jRadioRES39;
    private javax.swing.JRadioButton jRadioRES40;
    private javax.swing.JRadioButton jRadioRES41;
    private javax.swing.JRadioButton jRadioRES42;
    private javax.swing.JRadioButton jRadioRES43;
    private javax.swing.JRadioButton jRadioRES44;
    private javax.swing.JRadioButton jRadioRES45;
    private javax.swing.JRadioButton jRadioRES46;
    private javax.swing.JRadioButton jRadioRES47;
    private javax.swing.JRadioButton jRadioRES48;
    // End of variables declaration//GEN-END:variables
}
